export interface GuideSuggestion {
  title: string;
  url: string;
  category: 'education' | 'life';
  keywords: string[];
  summary?: string;
}

const GUIDE_DATABASE: GuideSuggestion[] = [
  { title: 'Словарь студенческого сленга', url: '/guides/education/slang-dictionary', category: 'education', keywords: ['сленг', 'студенческий сленг', 'стипуха', 'slang'] },
  { title: 'Как проходит обучение в вузе', url: '/guides/education/how-studies-work', category: 'education', keywords: ['обучение', 'семестр', 'лекция', 'семинар', 'учебный процесс', 'пары', 'университет', 'разобраться с университетом', 'как устроен вуз', 'международный отдел', 'деканат', 'кампус', 'структура вуза'], summary: 'В российском вузе обычно помогают: куратор, международный отдел, деканат/кафедра. Разберитесь с расписанием, личным кабинетом, правилами посещения и контактами поддержки.' },
  { title: 'Разница между экзаменом и зачётом', url: '/guides/education/exam-vs-credit', category: 'education', keywords: ['экзамен*', 'зачёт*', 'зачет*', 'оценка', 'балл', 'пятёрка'] },
  { title: 'Как подготовиться к сессии', url: '/guides/education/session', category: 'education', keywords: ['сесси*', 'подготовка', 'готовиться', 'конспект', 'шпаргалка', 'пересдача'] },
  { title: 'Как написать курсовую работу', url: '/guides/education/coursework', category: 'education', keywords: ['курсов*', 'курсовой', 'научная работа', 'оформление', 'введение', 'заключение', 'диплом', 'дипломная'] },
  { title: 'Оформление документов для вуза', url: '/guides/education/edu-academic-docs', category: 'education', keywords: ['справка', 'заявление', 'деканат', 'приёмная', 'ведомость'] },
  { title: 'Как не быть отчисленным', url: '/guides/education/expulsion-academic', category: 'education', keywords: ['отчисление', 'отчислен*', 'долг', 'задолженность', 'пропуск', 'академическ*'] },
  { title: 'Стипендии и гранты', url: '/education-guide?q=стипендия', category: 'education', keywords: ['стипенди*', 'грант', 'финансовая помощь', 'выплата', 'бюджет'] },
  { title: 'Расписание и учебный план', url: '/education-guide?q=расписание', category: 'education', keywords: ['расписание', 'график', 'учебный план', 'модуль', 'звонок'] },
  { title: 'Как зарегистрироваться в общежитии', url: '/guides/life/dorm', category: 'life', keywords: ['общежити*', 'заселение', 'комната', 'жильё', 'проживание', 'dormitory', 'общага'] },
  { title: 'Транспорт и проезд', url: '/guides/life/transport', category: 'life', keywords: ['транспорт', 'метро', 'автобус', 'троллейбус', 'проезд', 'карта тройка', 'маршрут'] },
  { title: 'Медицинская помощь', url: '/guides/life/call-doctor', category: 'life', keywords: ['врач*', 'больница', 'поликлиника', 'страховка', 'медицина', 'здоровье', 'аптека', 'лекарств*'] },
  { title: 'Банки и финансы', url: '/guides/life/bank', category: 'life', keywords: ['банк', 'банке', 'банка', 'банки', 'банковск*', 'банкомат*', 'деньги', 'счёт', 'счет', 'валюта', 'сбербанк', 'денежный перевод', 'денежного перевода', 'перевод денег', 'перевести деньги', 'обмен валют', 'bank account', 'money transfer', 'compte bancaire', 'virement bancaire', 'cuenta bancaria', 'transferencia bancaria', 'حساب بنكي', 'تحويل الأموال', '银行账户', '银行转账'] },
  { title: 'SIM-карта и связь', url: '/guides/life/sim-card', category: 'life', keywords: ['sim', 'телефон', 'связь', 'интернет', 'оператор', 'тариф', 'мтс', 'билайн', 'мегафон'] },
  {
    title: 'Регистрация и миграционный учёт',
    url: '/guides/life/migration-registration',
    category: 'life',
    keywords: ['регистрация', 'миграц*', 'виза', 'визу', 'визы', 'визе', 'патент', 'разрешение', 'мвд', 'уфмс', 'учёт', 'migration'],
    summary: 'После приезда иностранный студент обычно проходит миграционный учёт (регистрацию по месту пребывания) через вуз/общежитие/принимающую сторону. Сроки и список документов уточняйте в международном отделе вуза и на официальных ресурсах МВД/Госуслуг.',
  },
  {
    title: 'Что делать после приезда',
    url: '/life-guide#life-guide-arrival',
    category: 'life',
    keywords: ['после приезда', 'приехал', 'первый день', 'первые шаги', 'аэропорт', 'arrival'],
    summary: 'Чеклист после приезда: куратор/международный отдел, заселение/адрес, миграционный учёт, SIM, банк, страховка, кампус. Конкретные сроки зависят от вуза и региона.',
  },
  {
    title: 'Потеря паспорта',
    url: '/guides/life/lost-passport',
    category: 'life',
    keywords: [
      'потерял паспорт',
      'потеря паспорта',
      'украли паспорт',
      'утеря паспорта',
      'потерял документы',
      'потеря документов',
      'утеря документов',
      'потерял документ',
      'украли документы',
    ],
    summary: 'При потере паспорта/документов: заявление в полицию, консульство/миграционные органы, уведомление вуза. Не путать с обычной регистрацией после приезда.',
  },
];

// Conservative matching: only the user's question, never incidental words
// generated by the model. Only explicitly marked stems allow suffixes.
export function findRelatedGuides(userMessage: string): GuideSuggestion[] {
  const text = userMessage.toLowerCase().normalize('NFKC');
  return GUIDE_DATABASE.map(guide => ({
    ...guide,
    score: guide.keywords.reduce((score, keyword) => {
      const stem = keyword.endsWith('*');
      const escaped = (stem ? keyword.slice(0, -1) : keyword).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      // Chinese phrases are not separated by spaces or word boundaries.
      const pattern = /\p{Script=Han}/u.test(keyword)
        ? new RegExp(escaped, 'u')
        : new RegExp('(?:^|[^\\p{L}\\p{N}])' + escaped + (stem ? '' : '(?=$|[^\\p{L}\\p{N}])'), 'u');
      return score + (pattern.test(text) ? (keyword.includes(' ') ? 2 : 1) : 0);
    }, 0),
  })).filter(guide => guide.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);
}
